[package]
name = "neosh"
version = "0.1.0"
license = "GPL-3.0"
repository = "https://github.com/NTBBloodbath/neosh"
edition = "2018"

[dependencies]
rlua = "0.17.1"
dirs = "4.0.0"
rustyline = "9.0.0"
