name: Build
on: [push, pull_request]

jobs:
  neosh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - uses: Swatinem/rust-cache@v1
      - name: Build NeoSH
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

